[workspace]
resolver = "2"

members = [
    "rest",
    "rest_tensors",
    "rest_libcint"
]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
#panic = "abort"

[profile.profiling]
inherits = "release"
debug = true
